IF OBJECT_ID PARAMETROS', 'U') IS NOT NULL
DROP TABLE PARAMETROS;

CREATE TABLE PARAMETROS (
  COD INT NOT NULL,
  NOME_FANTASIA VARCHAR(100),
  RAZAO_SOCIAL VARCHAR(100),
  CNPJ VARCHAR(14),
  ENDERECO VARCHAR(50),
  NUMERO VARCHAR(10),
  COMPLEMENTO VARCHAR(50),
  BAIRRO CHAR(30),
  CIDADE CHAR(30),
  CEP CHAR(8),
  CONTDISCIPLINAS INTEGER,
  CONTPROFESSORES INTEGER,
  CONTALUNOS INTEGER
)
GO

ALTER TABLE PARAMETROS
ADD CONSTRAINT PK_PARAMETROS
PRIMARY KEY (COD)
GO
---------------------------------------------

IF OBJECT_ID ('DISCIPLINAS', 'U') IS NOT NULL
DROP TABLE DISCIPLINAS;

CREATE TABLE DISCIPLINAS (
	COD INT NOT NULL,
	DESCRICAO VARCHAR (50)

)
GO

ALTER TABLE DISCIPLINAS
ADD CONSTRAINT PK_DISCIPLINAS
PRIMARY KEY (COD)
GO

------------------------------------------
IF OBJECT_ID PROFESSORES', 'U') IS NOT NULL
DROP TABLE PROFESSORES;

CREATE TABLE PROFESSORES (
  COD INT NOT NULL,
  NOME CHAR(100),
  CPF CHAR(11),
  ENDERECO VARCHAR(50),
  NUMERO VARCHAR(10),
  COMPLEMENTO VARCHAR(50),
  BAIRRO CHAR(30),
  CIDADE CHAR(30),
  CEP CHAR(8),
  COD_DISCIPLINA INT
)
GO

ALTER TABLE PROFESSORES
ADD CONSTRAINT PK_PROFESSORES
PRIMARY KEY (COD)
GO

ALTER TABLE PROFESSORES
ADD CONSTRAINT FK_COD_DISCIPLINA
FOREIGN KEY (COD_DISCIPLINA)
REFERENCES DISCIPLINAS(COD);

------------------------------------------
IF OBJECT_ID ALUNOS', 'U') IS NOT NULL
DROP TABLE ALUNOS;

CREATE TABLE ALUNOS (
  COD INT NOT NULL,
  NOME CHAR(100),
  CPF CHAR(11),
  ENDERECO VARCHAR(50),
  NUMERO VARCHAR(10),
  COMPLEMENTO VARCHAR(50),
  BAIRRO CHAR(30),
  CIDADE CHAR(30),
  CEP CHAR(8)
)
GO

ALTER TABLE ALUNOS
ADD CONSTRAINT PK_ALUNOS
PRIMARY KEY (COD)
GO

------------------------------------------
IF OBJECT_ID DISCIPLINA_ALUNO', 'U') IS NOT NULL
DROP TABLE DISCIPLINA_ALUNO;

CREATE TABLE DISCIPLINA_ALUNO (
  COD_ALUNO INT NOT NULL,
  COD_DISCIPLINA INT NOT NULL,
  NOTA_PER1 NUMERIC(15,2),
  NOTA_PER2 NUMERIC(15,2),
  NOTA_TRABALHO NUMERIC(15,2),
  MEDIA NUMERIC(15,2)
)
GO

ALTER TABLE DISCIPLINA_ALUNO
ADD CONSTRAINT PK_DISCIPLINA_ALUNO
PRIMARY KEY (COD_ALUNO,COD_DISCIPLINA)


ALTER TABLE DISCIPLINA_ALUNO
ADD CONSTRAINT FK_COD_DISCIPLINA2
FOREIGN KEY (COD_DISCIPLINA)
REFERENCES DISCIPLINAS(COD)

ALTER TABLE DISCIPLINA_ALUNO
ADD CONSTRAINT FK_COD_ALUNO
FOREIGN KEY (COD_ALUNO)
REFERENCES ALUNOS(COD)
